export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_RECENTS_VISIBILITY = 'UPDATE_RECENTS_VISIBILITY';
export const UPDATE_LYRICS_VISIBILITY = 'UPDATE_LYRICS_VISIBILITY';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const UPDATE_NO_RESULTS = 'UPDATE_NO_RESULTS';



